version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_wordpress
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 0
    volumes:
      - wordpress_data:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      db:
        condition: service_healthy
    networks:
      - wordpress_network

  redis:
    image: redis:7-alpine
    container_name: wordpress_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
      MYSQL_ROOT_PASSWORD: wordpress123
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pwordpress123"]
      timeout: 20s
      retries: 10

volumes:
  wordpress_data:
  db_data:
  redis_data:

networks:
  wordpress_network:
    driver: bridge
