groups:
  - name: microservices
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Service {{ $labels.service }} has error rate of {{ $value }} errors per second"

      # High response time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "Service {{ $labels.service }} has 95th percentile response time of {{ $value }} seconds"

      # Service down
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Service {{ $labels.job }} is using {{ $value }} MB of memory"

      # High CPU usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "Service {{ $labels.job }} has CPU usage of {{ $value }}"

      # Database connection issues
      - alert: DatabaseConnectionFailed
        expr: up{job=~"postgres|mongodb|redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failed"
          description: "Database {{ $labels.job }} is not responding"

      # Low disk space
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is running low on {{ $labels.instance }}"

  - name: business_metrics
    rules:
      # High order volume
      - alert: HighOrderVolume
        expr: rate(orders_created_total[5m]) > 10
        for: 2m
        labels:
          severity: info
        annotations:
          summary: "High order volume"
          description: "Order creation rate is {{ $value }} orders per second"

      # Payment failure rate
      - alert: HighPaymentFailureRate
        expr: rate(payments_failed_total[5m]) / rate(payments_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High payment failure rate"
          description: "Payment failure rate is {{ $value }}%"

      # Low inventory
      - alert: LowInventory
        expr: product_stock < 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Low inventory"
          description: "Product {{ $labels.product_id }} has only {{ $value }} items in stock"
