# Enterprise AlertManager Configuration
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@enterprise.com'
  smtp_auth_username: 'alerts@enterprise.com'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://localhost:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'admin@enterprise.com'
    subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Job: {{ .Labels.job }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  webhook_configs:
  - url: 'http://localhost:5001/critical'
    send_resolved: true

- name: 'warning-alerts'
  email_configs:
  - to: 'ops@enterprise.com'
    subject: 'WARNING: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Job: {{ .Labels.job }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  webhook_configs:
  - url: 'http://localhost:5001/warning'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
